export const teamMembers = [
  {
    name: "Ranjana",
    role: "Chairperson",
    bio: "Leads the team with strategic vision, ensuring the success of all events and initiatives.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Ranjana_Chair.jpg?raw=true",
    social: {},
  },
  {
    name: "Priyanshu",
    role: "Tech Head",
    bio: "Oversees all technical aspects of the event, from software development to hardware integration.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Images/PRIYANSHU%20ISE%20(%20TECHNICAL%20HEAD).jpg?raw=true",
    social: {},
  },
  {
    name: "Abhinav",
    role: "Secretary",
    bio: "Manages documentation, official communications, and coordination between different teams.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Abhinav_EEE_.jpg?raw=true",
    social: {},
  },
  {
    name: "Ravisagar",
    role: "Treasurer",
    bio: "Handles financial planning, budgeting, and fund management for the event.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Ravisagar_BT.jpg?raw=true",
    social: {},
  },
  {
    name: "Deekshitha",
    role: "Convernor",
    bio: "Coordinates event execution, logistics, and overall festival planning.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Deekshitha_Convenor.jpg?raw=true",
    social: {},
  },
  {
    name: "Ryan Gomez",
    role: "Vice-Chair",
    bio: "Supports the Chairperson in decision-making and event oversight.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Images/IMG_7510.jpg?raw=true",
    social: {},
  },
  {
    name: "Aditya G",
    role: "Vice-Secretary",
    bio: "Assists in documentation and administrative tasks for smooth event operations.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/ADITYA%20GANGWANI_VICE%20SECRETARY.png?raw=true",
    social: {},
  },
  {
    name: "Shaikh Furkan",
    role: "Vice-Treasurer",
    bio: "Aids in financial management, sponsorship coordination, and fund allocation.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Shaikh%20Furqan.jpg?raw=true",
    social: {},
  },
  {
    name: "Shivesh Tiwari",
    role: "Vice-Tech Head",
    bio: "Assists in managing the technical infrastructure and digital aspects of the event.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Shivesh%20Tiwari_SB_Vice%20Technical%20Head.jpg?raw=true",
    social: {},
  },
  {
    name: "Navya",
    role: "Vice-Convernor",
    bio: "Helps in coordinating logistics and event scheduling for seamless execution.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Navya%20Ullas%20Rai_Vice-Convenor.jpg?raw=true",
    social: {},
  },
  {
    name: "Nagashree",
    role: "Social Media Head",
    bio: "Leads the social media team in content creation, marketing strategy, and audience engagement.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/nagashree.jpeg?raw=true",
    social: {},
  },
  {
    name: "Sanjay U",
    role: "Web Resources Head",
    bio: "Leads web development and online resource management for the event.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Sanjay.png?raw=true",
    social: {},
  },
  {
    name: "Abhishek V K",
    role: "Web Resources Co-Head",
    bio: "Assists in web resource management and development tasks.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Abhishek.png?raw=true",
    social: {},
  },
  {
    name: "Vedang",
    role: "Web Resource Developer",
    bio: "Develops and maintains web platforms for event information and registrations.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Vedang.jpeg?raw=true",
    social: {},
  },
  {
    name: "Karan",
    role: "Web Resource Developer",
    bio: "Works on the event website, ensuring smooth user experience and performance.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Karan.jpeg?raw=true",
    social: {},
  },
  {
    name: "Manjeet Roy",
    role: "Web Resource Developer",
    bio: "Works on the event website, ensuring smooth user experience and performance.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/manjeet.jpeg?raw=true",
    social: {},
  },
  {
    name: "Vishwas",
    role: "CS(AIML)-Coordinator",
    bio: "Coordinates AI & ML events, ensuring technical accuracy and engagement.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Vishwas_CSE(Aiml).jpg?raw=true",
    social: {},
  },
  {
    name: "Animmeth",
    role: "MBA Coordinator",
    bio: "Facilitates business and management-related events during the fest.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Animeeth%20Ghosh%20MBA.jpg?raw=true",
    social: {},
  },
  {
    name: "Darshan Karekar",
    role: "MCA-Coordinator",
    bio: "Organizes events focused on computer applications and software development.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Darshan%20Karekar%20MCA.jpg?raw=true",
    social: {},
  },
  {
    name: "HG Vashudeva",
    role: "AIML-Coordinator",
    bio: "Manages AI & ML-related events and workshops.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/H%20G%20Vasudeva_AIML.jpg?raw=true",
    social: {},
  },
  {
    name: "Jeevitha",
    role: "MCA-Coordinator",
    bio: "Oversees MCA-related tech events and workshops.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Jeevitha%20(MCA).jpg?raw=true",
    social: {},
  },
  {
    name: "Kannan",
    role: "Mech-Coordinator",
    bio: "Manages mechanical engineering-related competitions and exhibitions.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Kannan_Mech.jpg?raw=true",
    social: {},
  },
  {
    name: "Meenakshi",
    role: "Aerospace-Coordinator",
    bio: "Coordinates aerospace-related technical events and challenges.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Meenakshi%20K_Aerospace.jpg?raw=true",
    social: {},
  },
  {
    name: "Praful Anand",
    role: "CS(CY)-Coordinator",
    bio: "Leads cybersecurity and ethical hacking-related events.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/PRAFULL%20ANAND_CSE(CY).jpg?raw=true",
    social: {},
  },
  {
    name: "Sameer",
    role: "ETE-Coordinator",
    bio: "Handles electronics and telecommunication-related event planning.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Sameer%20P%20Bhandiwad_ETE.jpg?raw=true",
    social: {},
  },
  {
    name: "Shriya",
    role: "AIDS-Coordinator",
    bio: "Manages AI & Data Science-related competitions and workshops.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Shriya_AI%26DS.jpg?raw=true",
    social: {},
  },
  {
    name: "Varsha Gowda",
    role: "MD-Coordinator",
    bio: "Coordinates medical device-related tech events.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Varsha%20Gowda_MD.jpg?raw=true",
    social: {},
  },
];
