export const teamMembers = [
  {
    name: "Ranjana",
    role: "Chairperson",
    bio: "Strategic leader driving innovative event management and organizational excellence.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Ranjana_Chair.jpg?raw=true",
    social: {},
  },
  {
    name: "Priyanshu",
    role: "Tech Head",
    bio: "Passionate developer creating cutting-edge solutions for hackathons and tech events.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Images/PRIYANSHU%20ISE%20(%20TECHNICAL%20HEAD).jpg?raw=true",
    social: {},
  },
  {
    name: "Abhinav",
    role: "Secretary",
    bio: "Creative designer crafting compelling visuals for tech-focused events.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Abhinav_EEE_.jpg?raw=true",
    social: {},
  },
  {
    name: "Ravisagar K",
    role: "Treasurer",
    bio: "Financial strategist ensuring fiscal transparency and organizational budget management.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Ravisagar_BT.jpg?raw=true",
    social: {},
  },
  {
    name: "Deekshita",
    role: "Convenor",
    bio: "Event coordination expert managing complex logistics and team communications.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Deekshitha_Convenor.jpg?raw=true",
    social: {},
  },
  {
    name: "Ryan Gomez",
    role: "Vice-Chair",
    bio: "Strategic support leader collaborating on organizational objectives and event management.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Images/IMG_7510.jpg?raw=true",
    social: {},
  },
  {
    name: "Aditya G",
    role: "Vice-Secretary",
    bio: "Administrative professional supporting key organizational and documentation functions.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/ADITYA%20GANGWANI_VICE%20SECRETARY.png?raw=true",
    social: {},
  },
  {
    name: "Shaikh Furkan",
    role: "Vice-Treasurer",
    bio: "Financial assistant tracking budgets and ensuring accurate financial reporting.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Shaikh%20Furqan.jpg?raw=true",
    social: {},
  },
  {
    name: "Nagashree NS",
    role: "Social Media Head",
    bio: "Digital communication strategist creating engaging content for online brand presence.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/nagashree.jpeg?raw=true",
    social: {},
  },
  {
    name: "Janis Lobo",
    role: "Design Head",
    bio: "Creative visionary leading design team's innovative and aesthetic direction.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Design%20Team/7.jpeg?raw=true",
    social: {},
  },
  {
    name: "Shivesh",
    role: "Vice-Tech Head",
    bio: "Technical support specialist solving complex challenges and supporting tech initiatives.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Shivesh%20Tiwari_SB_Vice%20Technical%20Head.jpg?raw=true",
    social: {},
  },
  {
    name: "Navya",
    role: "Vice-Convernor",
    bio: "Event coordination professional facilitating smooth implementation of organizational activities.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Navya%20Ullas%20Rai_Vice-Convenor.jpg?raw=true",
    social: {},
  },
  {
    name: "Sanjay U",
    role: "Web Resources Head",
    bio: "Web technology expert managing digital infrastructure and online platform performance.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Sanjay.png?raw=true",
    social: {},
  },
  {
    name: "Abhishek V K",
    role: "Web Resources Co-Head",
    bio: "Web development professional supporting digital platform management and technical solutions.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Abhishek.png?raw=true",
    social: {},
  },
  {
    name: "Hiba",
    role: "Design Vice-Head",
    bio: "Creative professional supporting design team's vision and innovative visual concepts.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Design%20Team/4.jpeg?raw=true",
    social: {},
  },
  {
    name: "Nibha",
    role: "Design Co-Head",
    bio: "Collaborative designer developing creative solutions and supporting design innovation.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Design%20Team/2.jpeg?raw=true",
    social: {},
  },
  {
    name: "Vishwas",
    role: "Web Resource Developer & CS(AIML)-Coordinator",
    bio: "Technology professional bridging web development and AI/ML with innovative solutions.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Vishwas_CSE(Aiml).jpg?raw=true",
    social: {},
  },
  {
    name: "Vedang",
    role: "Web Resource Developer",
    bio: "Web development professional creating robust digital platforms and technical solutions.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Vedang.jpeg?raw=true",
    social: {},
  },
  {
    name: "Karan",
    role: "Web Resource Developer",
    bio: "Detail-oriented developer creating responsive interfaces and implementing web technologies.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Karan.jpeg?raw=true",
    social: {},
  },
  {
    name: "Nirmith",
    role: "Web Resource Developer",
    bio: "Creative developer building innovative digital solutions and enhancing user experiences.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/web_team/1.jpeg?raw=true",
    social: {},
  },
  {
    name: "Rayyan",
    role: "Web Resource Developer",
    bio: "Innovative developer creating dynamic platforms and solving complex technical challenges.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/web_team/3.jpeg?raw=true",
    social: {},
  },
  {
    name: "Naomi",
    role: "Web Resource Developer",
    bio: "Versatile developer creating scalable digital solutions with fresh technological perspectives.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/web_team/2.jpeg?raw=true",
    social: {},
  },
  {
    name: "Manjeet Roy",
    role: "Web Resource Developer",
    bio: "Experienced developer optimizing user experiences and ensuring technological performance.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/manjeet.jpeg?raw=true",
    social: {},
  },
  {
    name: "Satyajeet",
    role: "Designer",
    bio: "Creative professional delivering innovative visual solutions for design team.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Design%20Team/8.jpeg?raw=true",
    social: {},
  },
  {
    name: "Kishan G",
    role: "Designer",
    bio: "Imaginative designer translating complex concepts into engaging visual narratives.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Design%20Team/6.jpeg?raw=true",
    social: {},
  },
  {
    name: "Aditi R",
    role: "Designer",
    bio: "Innovative designer creating powerful visual concepts and brand identities.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Design%20Team/9.jpeg?raw=true",
    social: {},
  },
  {
    name: "Kavana",
    role: "Designer",
    bio: "Visual communication expert crafting elegant design solutions with strategic messaging.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Design%20Team/5.jpeg?raw=true",
    social: {},
  },
  {
    name: "Ojasvi",
    role: "Designer",
    bio: "Artistic professional bringing unique creative perspectives to visual design.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Design%20Team/1.jpeg?raw=true",
    social: {},
  },
  {
    name: "Rishi Raj",
    role: "Designer",
    bio: "Design innovator creating visually compelling solutions with strategic communication.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Design%20Team/3.jpeg?raw=true",
    social: {},
  },
  {
    name: "Animmeth",
    role: "MBA Coordinator",
    bio: "Business management professional bridging academic insights with industry perspectives.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Animeeth%20Ghosh%20MBA.jpg?raw=true",
    social: {},
  },
  {
    name: "Darshan Karekar",
    role: "MCA-Coordinator",
    bio: "Technology education specialist fostering innovative learning in computational sciences.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Darshan%20Karekar%20MCA.jpg?raw=true",
    social: {},
  },
  {
    name: "HG Vashudeva",
    role: "AIML-Coordinator",
    bio: "AI and Machine Learning expert driving innovation in data science.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/H%20G%20Vasudeva_AIML.jpg?raw=true",
    social: {},
  },
  {
    name: "Jeevitha",
    role: "MCA-Coordinator",
    bio: "Technology education professional enhancing student learning in computational technologies.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Jeevitha%20(MCA).jpg?raw=true",
    social: {},
  },
  {
    name: "Kannan",
    role: "Mech-Coordinator",
    bio: "Mechanical engineering specialist bridging academic learning with industrial perspectives.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Kannan_Mech.jpg?raw=true",
    social: {},
  },
  {
    name: "Meenakshi",
    role: "Aerospace-Coordinator",
    bio: "Aerospace engineering expert exploring frontiers of research and technological development.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Meenakshi%20K_Aerospace.jpg?raw=true",
    social: {},
  },
  {
    name: "Raveena",
    role: "Chemical-Coordinator",
    bio: "Chemical engineering professional fostering innovation in scientific technological applications.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Raveena%20SK_Chemical.jpg?raw=true",
    social: {},
  },
  {
    name: "Praful Anand",
    role: "CS(CY)-Coordinator",
    bio: "Cybersecurity specialist driving innovation in digital security and computing.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/PRAFULL%20ANAND_CSE(CY).jpg?raw=true",
    social: {},
  },
  {
    name: "Sameer",
    role: "ETE-Coordinator",
    bio: "Electronics and telecommunication expert bridging academic insights with communication technologies.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Sameer%20P%20Bhandiwad_ETE.jpg?raw=true",
    social: {},
  },
  {
    name: "Shriya",
    role: "AIDS-Coordinator",
    bio: "Data science professional driving innovation in interdisciplinary technological solutions.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Shriya_AI%26DS.jpg?raw=true",
    social: {},
  },
  {
    name: "Varsha Gowda",
    role: "MD-Coordinator",
    bio: "Medical technology specialist supporting innovation in healthcare and medical education.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Varsha%20Gowda_MD.jpg?raw=true",
    social: {},
  },
  {
    name: "Devika",
    role: "EI-Coordinator",
    bio: "Electronics engineering professional driving innovation in precision technological solutions.",
    image: "https://github.com/Abhishekvk04/TechFest/blob/main/SB/Devika%20N_%20EIE.jpg?raw=true",
    social: {},
  },
];